name: Generate Site

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 7,14 * * *"

jobs:
  generate-site:
    name: Generate Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install gnuplot
      run: sudo apt-get -y install libsm6 libice6 gnuplot

    - name: Install gems
      run: bundle install

    - name: Build site
      run: bundle exec generate-site

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Build site"
        branch: "published-site"
        commit_options: '--no-verify'
        file_pattern: public
